# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrace.proto\"\xf7\x01\n\x05Trace\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.Trace.Type\x12\x1f\n\x07pattern\x18\x02 \x01(\x0e\x32\x0e.Trace.Pattern\x12\x1d\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\r.Trace.Action\x12\x12\n\ntransition\x18\x04 \x01(\x08\x12\r\n\x05state\x18\x05 \x01(\r\"\x1f\n\x04Type\x12\n\n\x06TYPE_I\x10\x00\x12\x0b\n\x07TYPE_II\x10\x01\",\n\x07Pattern\x12\r\n\tRECOGNIZE\x10\x00\x12\n\n\x06\x46ORGET\x10\x01\x12\x06\n\x02NA\x10\x02\"!\n\x06\x41\x63tion\x12\n\n\x06REWARD\x10\x00\x12\x0b\n\x07PENALTY\x10\x01\"\x1f\n\x06Traces\x12\x15\n\x05trace\x18\x01 \x03(\x0b\x32\x06.Traceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trace_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACE._serialized_start=16
  _TRACE._serialized_end=263
  _TRACE_TYPE._serialized_start=151
  _TRACE_TYPE._serialized_end=182
  _TRACE_PATTERN._serialized_start=184
  _TRACE_PATTERN._serialized_end=228
  _TRACE_ACTION._serialized_start=230
  _TRACE_ACTION._serialized_end=263
  _TRACES._serialized_start=265
  _TRACES._serialized_end=296
# @@protoc_insertion_point(module_scope)
