# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsetlin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtsetlin.proto\":\n\x06\x43lause\x12\x11\n\tn_feature\x18\x01 \x01(\r\x12\x0f\n\x07n_state\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\r\"q\n\x10\x43lauseCompressed\x12\x15\n\rn_pos_literal\x18\x01 \x01(\r\x12\x15\n\rn_neg_literal\x18\x02 \x01(\r\x12\x0f\n\x07n_state\x18\x03 \x01(\r\x12\x10\n\x08position\x18\x04 \x03(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\r\"\xb9\x01\n\x07Tsetlin\x12\x0f\n\x07n_class\x18\x01 \x01(\r\x12\x11\n\tn_feature\x18\x02 \x01(\r\x12\x10\n\x08n_clause\x18\x03 \x01(\r\x12\x0f\n\x07n_state\x18\x04 \x01(\r\x12\x1e\n\nmodel_type\x18\x05 \x01(\x0e\x32\n.ModelType\x12\x18\n\x07\x63lauses\x18\x06 \x03(\x0b\x32\x07.Clause\x12-\n\x12\x63lauses_compressed\x18\x07 \x03(\x0b\x32\x11.ClauseCompressed*8\n\tModelType\x12\r\n\tINFERENCE\x10\x00\x12\x0c\n\x08TRAINING\x10\x01\x12\x0e\n\nCOMPRESSED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tsetlin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELTYPE._serialized_start=380
  _MODELTYPE._serialized_end=436
  _CLAUSE._serialized_start=17
  _CLAUSE._serialized_end=75
  _CLAUSECOMPRESSED._serialized_start=77
  _CLAUSECOMPRESSED._serialized_end=190
  _TSETLIN._serialized_start=193
  _TSETLIN._serialized_end=378
# @@protoc_insertion_point(module_scope)
