# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tsetlin.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'tsetlin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtsetlin.proto\"\x16\n\x06\x43lause\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\r\"`\n\x10\x43lauseCompressed\x12\x15\n\rn_pos_literal\x18\x01 \x01(\r\x12\x15\n\rn_neg_literal\x18\x02 \x01(\r\x12\x10\n\x08position\x18\x04 \x03(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\r\"d\n\x16\x43lauseCompressedOffset\x12\x15\n\rn_pos_literal\x18\x01 \x01(\r\x12\x15\n\rn_neg_literal\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x04 \x03(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\r\":\n\x17\x43lauseCompressedBitpack\x12\x11\n\tn_literal\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\r\"\xb3\x02\n\x07Tsetlin\x12\x0f\n\x07n_class\x18\x01 \x01(\r\x12\x11\n\tn_feature\x18\x02 \x01(\r\x12\x10\n\x08n_clause\x18\x03 \x01(\r\x12\x0f\n\x07n_state\x18\x04 \x01(\r\x12\x1e\n\nmodel_type\x18\x05 \x01(\x0e\x32\n.ModelType\x12\x18\n\x07\x63lauses\x18\x06 \x03(\x0b\x32\x07.Clause\x12-\n\x12\x63lauses_compressed\x18\x07 \x03(\x0b\x32\x11.ClauseCompressed\x12:\n\x19\x63lauses_compressed_offset\x18\x08 \x03(\x0b\x32\x17.ClauseCompressedOffset\x12<\n\x1a\x63lauses_compressed_bitpack\x18\t \x03(\x0b\x32\x18.ClauseCompressedBitpack*g\n\tModelType\x12\r\n\tINFERENCE\x10\x00\x12\x0c\n\x08TRAINING\x10\x01\x12\x0e\n\nCOMPRESSED\x10\x02\x12\x15\n\x11\x43OMPRESSED_OFFSET\x10\x03\x12\x16\n\x12\x43OMPRESSED_BITPACK\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tsetlin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELTYPE']._serialized_start=611
  _globals['_MODELTYPE']._serialized_end=714
  _globals['_CLAUSE']._serialized_start=17
  _globals['_CLAUSE']._serialized_end=39
  _globals['_CLAUSECOMPRESSED']._serialized_start=41
  _globals['_CLAUSECOMPRESSED']._serialized_end=137
  _globals['_CLAUSECOMPRESSEDOFFSET']._serialized_start=139
  _globals['_CLAUSECOMPRESSEDOFFSET']._serialized_end=239
  _globals['_CLAUSECOMPRESSEDBITPACK']._serialized_start=241
  _globals['_CLAUSECOMPRESSEDBITPACK']._serialized_end=299
  _globals['_TSETLIN']._serialized_start=302
  _globals['_TSETLIN']._serialized_end=609
# @@protoc_insertion_point(module_scope)
