# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tsetlin.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'tsetlin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtsetlin.proto\":\n\x06\x43lause\x12\x11\n\tn_feature\x18\x01 \x01(\r\x12\x0f\n\x07n_state\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\"\x8a\x01\n\x07Tsetlin\x12\x0f\n\x07n_class\x18\x01 \x01(\r\x12\x11\n\tn_feature\x18\x02 \x01(\r\x12\x10\n\x08n_clause\x18\x03 \x01(\r\x12\x0f\n\x07n_state\x18\x04 \x01(\r\x12\x1e\n\nmodel_type\x18\x05 \x01(\x0e\x32\n.ModelType\x12\x18\n\x07\x63lauses\x18\x06 \x03(\x0b\x32\x07.Clause*(\n\tModelType\x12\r\n\tINFERENCE\x10\x00\x12\x0c\n\x08TRAINING\x10\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tsetlin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELTYPE']._serialized_start=218
  _globals['_MODELTYPE']._serialized_end=258
  _globals['_CLAUSE']._serialized_start=17
  _globals['_CLAUSE']._serialized_end=75
  _globals['_TSETLIN']._serialized_start=78
  _globals['_TSETLIN']._serialized_end=216
# @@protoc_insertion_point(module_scope)
