"""ATTENTION! This module is autogenerated! Don't edit!"""

from protobuf.uprotobuf import Message, Field, Enum

PACKAGE=''

class Tsetlin(Message):
    _fields=[
        Field(name='n_class', type='UInt32', id=1, required=True),
        Field(name='n_feature', type='UInt32', id=2, required=True),
        Field(name='n_clause', type='UInt32', id=3, required=True),
        Field(name='n_state', type='UInt32', id=4, required=True),
        Field(name='clause', type='Int32', id=5, repeated=True),
    ]
